services:
  initial_ingestion:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./src/.env
    container_name: discord_rag_initial_ingestion
    networks:
      - discord_rag_network

networks:
  discord_rag_network:
    name: discord_rag_network
    driver: bridge
    external: true