services:
  indexing_pipeline:
    build:
      context: ../
      dockerfile: ./indexing_pipeline/Dockerfile
    env_file:
      - .env
    container_name: discord_rag_indexing_pipeline
    networks:
      - discord_rag_network

networks:
  discord_rag_network:
    name: discord_rag_network
    driver: bridge
    external: true